# Generated by Django 4.2 on 2024-11-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_video_tags'),
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history_video',
            field=models.ManyToManyField(blank=True, related_name='history_video', to='core.video'),
        ),
    ]
