# Generated by Django 4.2 on 2024-10-30 02:40

import channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_art', models.ImageField(default='images/channel-art.jpg', upload_to=channel.models.user_derectory_path)),
                ('image', models.ImageField(default='images/user-image.png', upload_to=channel.models.user_derectory_path)),
                ('full_name', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='Active', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('make_business_email_public', models.BooleanField(default=False)),
                ('business_location', models.CharField(blank=True, max_length=100, null=True)),
                ('make_business_location_public', models.BooleanField(default=False)),
                ('website', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('facebook', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('subscibers', models.ManyToManyField(related_name='user_subs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
