# Generated by Django 4.2 on 2024-11-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='subscibers',
            new_name='subscribers',
        ),
    ]
