# Generated by Django 4.2 on 2024-10-31 01:33

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(default='images/channel-art.jpgpython', upload_to=channel.models.user_derectory_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='facebook',
            field=models.URLField(default='https://www.udemy.com/home'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='instagram',
            field=models.URLField(default='https://www.udemy.com/home'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='twitter',
            field=models.URLField(default='https://www.udemy.com/home'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='website',
            field=models.URLField(default='https://www.udemy.com/home'),
        ),
    ]
