# Generated by Django 4.2 on 2024-11-03 05:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('channel', '0002_rename_subscibers_channel_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='keyword',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
