# Generated by Django 4.2 on 2024-11-04 02:11

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(default='images/channel-art.jpg', upload_to=channel.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='images/user-image.png', upload_to=channel.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=channel.models.user_directory_path),
        ),
    ]
