# Generated by Django 4.2 on 2024-11-08 00:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channel_channel_art_alter_channel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(default='images/channel-art.jpg', upload_to=core.models.user_derectory_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='images/user-image.png', upload_to=core.models.user_derectory_path),
        ),
    ]
